import Header from './components/Header'
import './globals.css'
import Mouse from './components/Mouse'
import React from 'react'
import Load from './components/Load'

export const metadata = {
  title: 'Rushikesh Gaonkar',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  <>
    <html lang="en">
      <body>
        <Load/>
        <Mouse/>
        <Header/>
        {children }
        </body>
        </html>
        </>
  )
}
